In [3]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("train.csv")

In [5]:
df.head()

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,1048,22,Female,B.Tech,ECE,6.29,0,3,4,6,51,5,1,3,Not Placed
1,37820,20,Female,BCA,ECE,6.05,1,4,6,8,59,8,2,1,Not Placed
2,49668,22,Male,MCA,ME,7.22,1,4,6,6,58,6,2,2,Not Placed
3,19467,22,Male,MCA,ME,7.78,2,4,6,6,90,4,2,0,Placed
4,23094,20,Female,B.Tech,ME,7.63,1,4,6,5,79,6,2,0,Placed

In [6]:
df.shape

(45000, 15)

In [7]:
df["Branch"].value_counts()

Branch
ME       9056
ECE      9026
CSE      8989
Civil    8981
IT       8948
Name: count, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop("Placement_Status", axis=1), df["Placement_Status"], test_size=0.2, random_state=42)

In [38]:
X_train.head(10)

,Student_ID,Age,Gender,Degree,Branch,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs
25180,14526,18,Female,MCA,ECE,7.44,0,3,4,3,79,5,1,0
12555,10564,20,Male,BCA,IT,6.80,0,3,3,5,69,6,1,0
29153,22252,23,Female,MCA,ECE,6.27,0,4,6,7,36,3,1,1
23838,30800,22,Female,BCA,ECE,7.49,2,4,7,5,82,3,2,0
35686,30320,18,Female,BCA,CSE,7.25,0,3,4,5,53,6,1,0
34245,41671,18,Female,B.Tech,ME,5.57,0,2,2,5,58,7,1,2
31360,28379,18,Female,BCA,ECE,6.41,1,4,6,6,58,5,2,1
31474,20220,24,Male,MCA,ME,5.92,1,3,6,3,49,7,2,2
15004,28181,23,Female,BCA,ECE,6.94,0,3,4,8,61,4,1,2
13082,49774,19,Male,B.Tech,ME,7.24,1,3,4,5,78,6,1,0

In [ ]:
X_train.shape

(36000, 14)

In [ ]:
y_train.shape

(36000,)

## **Without Column Transformer**

**One Hot Encoding on Gender & Branch**

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [12]:
X_train_ohe = ohe.fit_transform(X_train[["Gender", "Branch"]])
X_test_ohe = ohe.transform(X_test[["Gender", "Branch"]])

In [13]:
X_train_ohe

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       ...,
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0]], dtype=int32)

In [14]:
X_train_ohe.shape

(36000, 5)

In [15]:
df_encoded = pd.DataFrame(X_train_ohe, columns=ohe.get_feature_names_out(["Gender", "Branch"]))

In [16]:
df_encoded.head(3)

   Gender_Male  Branch_Civil  Branch_ECE  Branch_IT  Branch_ME
0            0             0           1          0          0
1            1             0           0          1          0
2            0             0           1          0          0

**Ordinal Encoding on Degree**

In [17]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
oe = OrdinalEncoder(categories=[["BCA", "B.Sc", "B.Tech", "MCA"]], dtype=np.int32)

In [19]:
X_train_oe = oe.fit_transform(X_train[["Degree"]])
X_test_oe = oe.transform(X_test[["Degree"]])

In [20]:
X_train_oe

array([[3],
       [0],
       [3],
       ...,
       [1],
       [1],
       [0]], dtype=int32)

In [21]:
X_train_oe.shape

(36000, 1)

**Label Encoding on Placement_Status**

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le = LabelEncoder()

In [24]:
y_train_le = le.fit_transform(y_train)
y_test_le = le.transform(y_test)

In [25]:
y_train_le

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
y_train_le.shape

(36000,)

**Now creating one Data Frame**

In [27]:
data = np.hstack((X_train.iloc[:,:2], X_train_ohe, X_train_oe, X_train.iloc[:, 5:], y_train_le.reshape(-1, 1)))

In [54]:
df_encoded = pd.DataFrame(data, columns=["Student_ID", "Age", "Male", "Civil", "ECE", "IT", "ME", "Degree", "CGPA", "Internships", "Projects",	"Coding_Skills",	"Communication_Skills",	"Aptitude_Test_Score",	"Soft_Skills_Rating",	"Certifications",	"Backlogs", "Placement_Status"])

In [55]:
df_encoded.shape

(36000, 18)

In [56]:
df_encoded.head(10)

,Student_ID,Age,Male,Civil,ECE,IT,ME,Degree,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,14526.0,18.0,0.0,0.0,1.0,0.0,0.0,3.0,7.44,0.0,3.0,4.0,3.0,79.0,5.0,1.0,0.0,0.0
1,10564.0,20.0,1.0,0.0,0.0,1.0,0.0,0.0,6.80,0.0,3.0,3.0,5.0,69.0,6.0,1.0,0.0,0.0
2,22252.0,23.0,0.0,0.0,1.0,0.0,0.0,3.0,6.27,0.0,4.0,6.0,7.0,36.0,3.0,1.0,1.0,0.0
3,30800.0,22.0,0.0,0.0,1.0,0.0,0.0,0.0,7.49,2.0,4.0,7.0,5.0,82.0,3.0,2.0,0.0,1.0
4,30320.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,7.25,0.0,3.0,4.0,5.0,53.0,6.0,1.0,0.0,0.0
5,41671.0,18.0,0.0,0.0,0.0,0.0,1.0,2.0,5.57,0.0,2.0,2.0,5.0,58.0,7.0,1.0,2.0,0.0
6,28379.0,18.0,0.0,0.0,1.0,0.0,0.0,0.0,6.41,1.0,4.0,6.0,6.0,58.0,5.0,2.0,1.0,0.0
7,20220.0,24.0,1.0,0.0,0.0,0.0,1.0,3.0,5.92,1.0,3.0,6.0,3.0,49.0,7.0,2.0,2.0,0.0
8,28181.0,23.0,0.0,0.0,1.0,0.0,0.0,0.0,6.94,0.0,3.0,4.0,8.0,61.0,4.0,1.0,2.0,0.0
9,49774.0,19.0,1.0,0.0,0.0,0.0,1.0,2.0,7.24,1.0,3.0,4.0,5.0,78.0,6.0,1.0,0.0,0.0

In [30]:
df[df["Student_ID"] == 14526].iloc[0]

Student_ID                   14526
Age                             18
Gender                      Female
Degree                         MCA
Branch                         ECE
CGPA                          7.44
Internships                      0
Projects                         3
Coding_Skills                    4
Communication_Skills             3
Aptitude_Test_Score             79
Soft_Skills_Rating               5
Certifications                   1
Backlogs                         0
Placement_Status        Not Placed
Name: 25180, dtype: object

## **With Column Transformer**

In [31]:
from sklearn.compose import ColumnTransformer

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop("Placement_Status", axis=1), df["Placement_Status"], test_size=0.2, random_state=42)

In [45]:
transformer = ColumnTransformer(transformers=[
    ("tnf1", OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32), ["Gender", "Branch"]),
    ("tnf2", OrdinalEncoder(categories=[["BCA", "B.Sc", "B.Tech", "MCA"]], dtype=np.int32), ["Degree"])
], remainder="passthrough")

In [47]:
X_train_col_encoded = transformer.fit_transform(X_train)
X_test_col_encoded = transformer.transform(X_test)

In [66]:
X_train_col_encoded

array([[0., 0., 1., ..., 5., 1., 0.],
       [1., 0., 0., ..., 6., 1., 0.],
       [0., 0., 1., ..., 3., 1., 1.],
       ...,
       [0., 0., 0., ..., 3., 1., 0.],
       [0., 0., 0., ..., 6., 1., 3.],
       [1., 0., 0., ..., 7., 1., 2.]])

In [61]:
data = np.hstack((X_train_col_encoded, y_train_le.reshape(-1, 1)))

In [70]:
df_col_encoded = pd.DataFrame(data, columns=["Male", "Civil", "ECE", "IT", "ME", "Degree", "Student_ID", "Age", "CGPA", "Internships", "Projects",	"Coding_Skills",	"Communication_Skills",	"Aptitude_Test_Score",	"Soft_Skills_Rating",	"Certifications",	"Backlogs", "Placement_Status"])

In [71]:
df_col_encoded.shape

(36000, 18)

In [72]:
df_col_encoded.head(10)

,Male,Civil,ECE,IT,ME,Degree,Student_ID,Age,CGPA,Internships,Projects,Coding_Skills,Communication_Skills,Aptitude_Test_Score,Soft_Skills_Rating,Certifications,Backlogs,Placement_Status
0,0.0,0.0,1.0,0.0,0.0,3.0,14526.0,18.0,7.44,0.0,3.0,4.0,3.0,79.0,5.0,1.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,10564.0,20.0,6.80,0.0,3.0,3.0,5.0,69.0,6.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,3.0,22252.0,23.0,6.27,0.0,4.0,6.0,7.0,36.0,3.0,1.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,30800.0,22.0,7.49,2.0,4.0,7.0,5.0,82.0,3.0,2.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,30320.0,18.0,7.25,0.0,3.0,4.0,5.0,53.0,6.0,1.0,0.0,0.0
5,0.0,0.0,0.0,0.0,1.0,2.0,41671.0,18.0,5.57,0.0,2.0,2.0,5.0,58.0,7.0,1.0,2.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0,28379.0,18.0,6.41,1.0,4.0,6.0,6.0,58.0,5.0,2.0,1.0,0.0
7,1.0,0.0,0.0,0.0,1.0,3.0,20220.0,24.0,5.92,1.0,3.0,6.0,3.0,49.0,7.0,2.0,2.0,0.0
8,0.0,0.0,1.0,0.0,0.0,0.0,28181.0,23.0,6.94,0.0,3.0,4.0,8.0,61.0,4.0,1.0,2.0,0.0
9,1.0,0.0,0.0,0.0,1.0,2.0,49774.0,19.0,7.24,1.0,3.0,4.0,5.0,78.0,6.0,1.0,0.0,0.0